// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using optiflow_platform.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace optiflow_platform.Shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707231750_WidenPatientPhoneColumn")]
    partial class WidenPatientPhoneColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("optiflow_platform.Analytics.Domain.Model.Aggregates.AnalyticsReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageDeliveryDays")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("average_delivery_days");

                    b.Property<decimal>("ConversionRate")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("conversion_rate");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_at");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("generated_by");

                    b.Property<decimal>("OnTimeDeliveryRate")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("on_time_delivery_rate");

                    b.Property<decimal>("PendingBalance0To7")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("pending_balance0_to7");

                    b.Property<decimal>("PendingBalance16To30")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("pending_balance16_to30");

                    b.Property<decimal>("PendingBalance8To15")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("pending_balance8_to15");

                    b.Property<decimal>("PendingBalanceOver30")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("pending_balance_over30");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("period");

                    b.Property<decimal>("ReworkRate")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("rework_rate");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("int")
                        .HasColumnName("total_orders");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_revenue");

                    b.Property<int>("TotalTransactions")
                        .HasColumnType("int")
                        .HasColumnName("total_transactions");

                    b.HasKey("Id")
                        .HasName("p_k_analytics_reports");

                    b.ToTable("analytics_reports");
                });

            modelBuilder.Entity("optiflow_platform.Analytics.Domain.Model.Entities.StaffMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("employee_name");

                    b.Property<int>("QuotationsIssued")
                        .HasColumnType("int")
                        .HasColumnName("quotations_issued");

                    b.Property<int>("ReportId")
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    b.Property<int>("SalesClosed")
                        .HasColumnType("int")
                        .HasColumnName("sales_closed");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_revenue");

                    b.HasKey("Id")
                        .HasName("p_k_staff_metrics");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("i_x_staff_metrics_report_id");

                    b.ToTable("staff_metrics");
                });

            modelBuilder.Entity("optiflow_platform.Clinical.Domain.Model.Aggregates.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birth_date");

                    b.Property<string>("CustomerUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("customer_uuid");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("p_k_patients");

                    b.HasIndex("CustomerUuid")
                        .IsUnique()
                        .HasDatabaseName("i_x_patients_customer_uuid");

                    b.HasIndex("AccountId", "Dni")
                        .IsUnique()
                        .HasDatabaseName("i_x_patients_account_id_dni");

                    b.ToTable("patients");
                });

            modelBuilder.Entity("optiflow_platform.Clinical.Domain.Model.Entities.ClinicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("ClinicalRecordUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clinical_record_uuid");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.HasKey("Id")
                        .HasName("p_k_clinical_records");

                    b.HasIndex("ClinicalRecordUuid")
                        .IsUnique()
                        .HasDatabaseName("i_x_clinical_records_clinical_record_uuid");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasDatabaseName("i_x_clinical_records_patient_id");

                    b.ToTable("clinical_records");
                });

            modelBuilder.Entity("optiflow_platform.Clinical.Domain.Model.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<decimal?>("Addition")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("addition");

                    b.Property<int>("ClinicalRecordId")
                        .HasColumnType("int")
                        .HasColumnName("clinical_record_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("doctor_name");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("OdAxis")
                        .HasColumnType("int")
                        .HasColumnName("od_axis");

                    b.Property<decimal>("OdCylinder")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("od_cylinder");

                    b.Property<decimal>("OdSphere")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("od_sphere");

                    b.Property<int>("OiAxis")
                        .HasColumnType("int")
                        .HasColumnName("oi_axis");

                    b.Property<decimal>("OiCylinder")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("oi_cylinder");

                    b.Property<decimal>("OiSphere")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("oi_sphere");

                    b.Property<string>("PrescriptionUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("prescription_uuid");

                    b.HasKey("Id")
                        .HasName("p_k_prescriptions");

                    b.HasIndex("ClinicalRecordId")
                        .HasDatabaseName("i_x_prescriptions_clinical_record_id");

                    b.HasIndex("PrescriptionUuid")
                        .IsUnique()
                        .HasDatabaseName("i_x_prescriptions_prescription_uuid");

                    b.ToTable("prescriptions");
                });

            modelBuilder.Entity("optiflow_platform.IAM.Domain.Model.Aggregates.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_accounts");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("optiflow_platform.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("google_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("optiflow_platform.IAM.Domain.Model.Entities.PasswordRecoveryToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_used");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_password_recovery_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("i_x_password_recovery_tokens_token_hash");

                    b.ToTable("password_recovery_tokens", (string)null);
                });

            modelBuilder.Entity("optiflow_platform.Inventory.Domain.Model.Aggregates.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("category");

                    b.Property<string>("LastRestockDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_restock_date");

                    b.Property<int>("MinimumStockThreshold")
                        .HasColumnType("int")
                        .HasColumnName("minimum_stock_threshold");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sku");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("supplier_name");

                    b.HasKey("Id")
                        .HasName("p_k_products");

                    b.HasIndex("AccountId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("i_x_products_account_id_sku");

                    b.ToTable("products");
                });

            modelBuilder.Entity("optiflow_platform.Inventory.Domain.Model.Aggregates.StockAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("author");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("date");

                    b.Property<int>("NewStock")
                        .HasColumnType("int")
                        .HasColumnName("new_stock");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("operation");

                    b.Property<int>("PreviousStock")
                        .HasColumnType("int")
                        .HasColumnName("previous_stock");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sku");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("time");

                    b.HasKey("Id")
                        .HasName("p_k_stock_audit_logs");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("i_x_stock_audit_logs_account_id");

                    b.ToTable("stock_audit_logs");
                });

            modelBuilder.Entity("optiflow_platform.Inventory.Domain.Model.Aggregates.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_suppliers");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_suppliers_account_id_name");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("optiflow_platform.LabAndOrders.Domain.Model.Aggregates.Laboratory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_laboratories");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_laboratories_account_id_name");

                    b.ToTable("laboratories");
                });

            modelBuilder.Entity("optiflow_platform.LabAndOrders.Domain.Model.Aggregates.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("DeliveryDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("delivery_date");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("deposit");

                    b.Property<string>("Frame")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("frame");

                    b.Property<int?>("FrameProductId")
                        .HasColumnType("int")
                        .HasColumnName("frame_product_id");

                    b.Property<bool>("IsRework")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_rework");

                    b.Property<int>("LaboratoryId")
                        .HasColumnType("int")
                        .HasColumnName("laboratory_id");

                    b.Property<string>("LaboratoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("laboratory_name");

                    b.Property<int?>("LensProductId")
                        .HasColumnType("int")
                        .HasColumnName("lens_product_id");

                    b.Property<string>("LensType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lens_type");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("patient_name");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("prescription");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("priority");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("recipe_id");

                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("sale_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("p_k_work_orders");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("i_x_work_orders_account_id");

                    b.ToTable("work_orders");
                });

            modelBuilder.Entity("optiflow_platform.PatientCenter.Domain.Model.Entities.LensMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("IndexValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("index_value");

                    b.HasKey("Id")
                        .HasName("p_k_lens_materials");

                    b.ToTable("lens_materials");
                });

            modelBuilder.Entity("optiflow_platform.PatientCenter.Domain.Model.Entities.PatientNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id")
                        .HasName("p_k_patient_notifications");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("i_x_patient_notifications_account_id");

                    b.ToTable("patient_notifications");
                });

            modelBuilder.Entity("optiflow_platform.Sales.Domain.Model.Aggregates.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("method");

                    b.Property<decimal>("OutstandingBalance")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("outstanding_balance");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("paid_amount");

                    b.Property<string>("PaidAt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("paid_at");

                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("sale_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("p_k_payments");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("i_x_payments_account_id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("optiflow_platform.Sales.Domain.Model.Aggregates.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Advance")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("advance");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveredAt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("delivered_at");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("discount_amount");

                    b.Property<string>("DiscountCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("discount_code");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("invoice_number");

                    b.Property<string>("LabOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lab_order_number");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("patient_name");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<decimal>("PendingBalance")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("pending_balance");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("p_k_sales");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("i_x_sales_account_id");

                    b.ToTable("sales");
                });

            modelBuilder.Entity("optiflow_platform.Sales.Domain.Model.Entities.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("sale_id");

                    b.HasKey("Id")
                        .HasName("p_k_sale_items");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("i_x_sale_items_account_id");

                    b.ToTable("sale_items");
                });

            modelBuilder.Entity("optiflow_platform.Shared.Domain.Model.Entities.SystemNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int")
                        .HasColumnName("recipient_user_id");

                    b.HasKey("Id")
                        .HasName("p_k_system_notifications");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("i_x_system_notifications_account_id");

                    b.ToTable("system_notifications");
                });

            modelBuilder.Entity("optiflow_platform.Staff.Domain.Model.Aggregates.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("display_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("permissions");

                    b.HasKey("Id")
                        .HasName("p_k_staff_roles");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_staff_roles_account_id_name");

                    b.ToTable("staff_roles", (string)null);
                });

            modelBuilder.Entity("optiflow_platform.Staff.Domain.Model.Aggregates.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<bool>("ActiveToday")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active_today");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("employee_code");

                    b.Property<string>("EntryDate")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entry_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Photo")
                        .HasColumnType("longtext")
                        .HasColumnName("photo");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_staff");

                    b.HasIndex("AccountId", "EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("i_x_staff_account_id_employee_code");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("optiflow_platform.Subscription.Domain.Model.Aggregates.Billing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("auto_renew");

                    b.Property<string>("BillingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("billing_status");

                    b.Property<DateTimeOffset>("RenewalDate")
                        .HasColumnType("datetime")
                        .HasColumnName("renewal_date");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("p_k_subscription_billings");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("i_x_subscription_billings_account_id");

                    b.ToTable("subscription_billings", (string)null);
                });

            modelBuilder.Entity("optiflow_platform.Subscription.Domain.Model.Aggregates.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("p_k_subscription_payments");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("i_x_subscription_payments_account_id");

                    b.ToTable("subscription_payments", (string)null);
                });

            modelBuilder.Entity("optiflow_platform.Subscription.Domain.Model.Aggregates.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("p_k_subscription_plans");

                    b.ToTable("subscription_plans", (string)null);
                });

            modelBuilder.Entity("optiflow_platform.Subscription.Domain.Model.Aggregates.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("p_k_subscriptions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("i_x_subscriptions_account_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("optiflow_platform.Analytics.Domain.Model.Entities.StaffMetric", b =>
                {
                    b.HasOne("optiflow_platform.Analytics.Domain.Model.Aggregates.AnalyticsReport", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_staff_metrics_analytics_reports_report_id");
                });

            modelBuilder.Entity("optiflow_platform.Clinical.Domain.Model.Entities.ClinicalRecord", b =>
                {
                    b.HasOne("optiflow_platform.Clinical.Domain.Model.Aggregates.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_clinical_records_patients_patient_id");
                });

            modelBuilder.Entity("optiflow_platform.Clinical.Domain.Model.Entities.Prescription", b =>
                {
                    b.HasOne("optiflow_platform.Clinical.Domain.Model.Entities.ClinicalRecord", null)
                        .WithMany()
                        .HasForeignKey("ClinicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_prescriptions_clinical_records_clinical_record_id");
                });

            modelBuilder.Entity("optiflow_platform.Inventory.Domain.Model.Aggregates.Supplier", b =>
                {
                    b.OwnsOne("optiflow_platform.Inventory.Domain.Model.ValueObjects.SupplierContact", "Contact", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("ContactPerson")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("contact_person");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("contact_phone");

                            b1.HasKey("Id")
                                .HasName("p_k_suppliers");

                            b1.ToTable("suppliers");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_suppliers_suppliers_id");
                        });

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("optiflow_platform.LabAndOrders.Domain.Model.Aggregates.Laboratory", b =>
                {
                    b.OwnsOne("optiflow_platform.LabAndOrders.Domain.Model.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("contact_phone");

                            b1.HasKey("Id")
                                .HasName("p_k_laboratories");

                            b1.ToTable("laboratories");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_laboratories_laboratories_id");
                        });

                    b.Navigation("ContactInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
