// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using optiflow_platform.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace optiflow_platform.Shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609020716_FixPendingChanges")]
    partial class FixPendingChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("optiflow_platform.Analytics.Domain.Model.Aggregates.AnalyticsReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageDeliveryDays")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("average_delivery_days");

                    b.Property<decimal>("ConversionRate")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("conversion_rate");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_at");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("generated_by");

                    b.Property<decimal>("OnTimeDeliveryRate")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("on_time_delivery_rate");

                    b.Property<decimal>("PendingBalance0To7")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("pending_balance0_to7");

                    b.Property<decimal>("PendingBalance16To30")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("pending_balance16_to30");

                    b.Property<decimal>("PendingBalance8To15")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("pending_balance8_to15");

                    b.Property<decimal>("PendingBalanceOver30")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("pending_balance_over30");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("period");

                    b.Property<decimal>("ReworkRate")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("rework_rate");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("int")
                        .HasColumnName("total_orders");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_revenue");

                    b.Property<int>("TotalTransactions")
                        .HasColumnType("int")
                        .HasColumnName("total_transactions");

                    b.HasKey("Id")
                        .HasName("p_k_analytics_reports");

                    b.ToTable("analytics_reports");
                });

            modelBuilder.Entity("optiflow_platform.Analytics.Domain.Model.Entities.StaffMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("employee_name");

                    b.Property<int>("QuotationsIssued")
                        .HasColumnType("int")
                        .HasColumnName("quotations_issued");

                    b.Property<int>("ReportId")
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    b.Property<int>("SalesClosed")
                        .HasColumnType("int")
                        .HasColumnName("sales_closed");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_revenue");

                    b.HasKey("Id")
                        .HasName("p_k_staff_metrics");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("i_x_staff_metrics_report_id");

                    b.ToTable("staff_metrics");
                });

            modelBuilder.Entity("optiflow_platform.Clinical.Domain.Model.Aggregates.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("p_k_patients");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasDatabaseName("i_x_patients_dni");

                    b.ToTable("patients");
                });

            modelBuilder.Entity("optiflow_platform.Clinical.Domain.Model.Entities.ClinicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.HasKey("Id")
                        .HasName("p_k_clinical_records");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasDatabaseName("i_x_clinical_records_patient_id");

                    b.ToTable("clinical_records");
                });

            modelBuilder.Entity("optiflow_platform.Clinical.Domain.Model.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("Addition")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("addition");

                    b.Property<int>("ClinicalRecordId")
                        .HasColumnType("int")
                        .HasColumnName("clinical_record_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("doctor_name");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("OdAxis")
                        .HasColumnType("int")
                        .HasColumnName("od_axis");

                    b.Property<decimal>("OdCylinder")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("od_cylinder");

                    b.Property<decimal>("OdSphere")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("od_sphere");

                    b.Property<int>("OiAxis")
                        .HasColumnType("int")
                        .HasColumnName("oi_axis");

                    b.Property<decimal>("OiCylinder")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("oi_cylinder");

                    b.Property<decimal>("OiSphere")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("oi_sphere");

                    b.HasKey("Id")
                        .HasName("p_k_prescriptions");

                    b.HasIndex("ClinicalRecordId")
                        .HasDatabaseName("i_x_prescriptions_clinical_record_id");

                    b.ToTable("prescriptions");
                });

            modelBuilder.Entity("optiflow_platform.Inventory.Domain.Model.Aggregates.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("category");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("LastRestockDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_restock_date");

                    b.Property<int>("MinimumStockThreshold")
                        .HasColumnType("int")
                        .HasColumnName("minimum_stock_threshold");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sku");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("supplier_name");

                    b.HasKey("Id")
                        .HasName("p_k_products");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("i_x_products_sku");

                    b.ToTable("products");
                });

            modelBuilder.Entity("optiflow_platform.Inventory.Domain.Model.Aggregates.StockAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("author");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("date");

                    b.Property<int>("NewStock")
                        .HasColumnType("int")
                        .HasColumnName("new_stock");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("operation");

                    b.Property<int>("PreviousStock")
                        .HasColumnType("int")
                        .HasColumnName("previous_stock");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sku");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("time");

                    b.HasKey("Id")
                        .HasName("p_k_stock_audit_logs");

                    b.ToTable("stock_audit_logs");
                });

            modelBuilder.Entity("optiflow_platform.Inventory.Domain.Model.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_categories");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("optiflow_platform.Inventory.Domain.Model.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contact_person");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("p_k_suppliers");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("optiflow_platform.LabAndOrders.Domain.Model.Aggregates.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DeliveryDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("delivery_date");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("deposit");

                    b.Property<string>("Frame")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("frame");

                    b.Property<bool>("IsRework")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_rework");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<string>("LaboratoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("laboratory_name");

                    b.Property<string>("LensType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lens_type");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("patient_name");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("prescription");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("priority");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("recipe_id");

                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("sale_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("p_k_work_orders");

                    b.ToTable("work_orders");
                });

            modelBuilder.Entity("optiflow_platform.LabAndOrders.Domain.Model.Entities.Laboratory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("contact_info");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_laboratories");

                    b.ToTable("laboratories");
                });

            modelBuilder.Entity("optiflow_platform.Sales.Domain.Model.Aggregates.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("OutstandingBalance")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("outstanding_balance");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("paid_amount");

                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("sale_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("p_k_payments");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("optiflow_platform.Sales.Domain.Model.Aggregates.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("client_name");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_percentage");

                    b.Property<decimal>("QuotaAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("quota_amount");

                    b.Property<string>("SaleDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sale_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("p_k_sales");

                    b.ToTable("sales");
                });

            modelBuilder.Entity("optiflow_platform.Analytics.Domain.Model.Entities.StaffMetric", b =>
                {
                    b.HasOne("optiflow_platform.Analytics.Domain.Model.Aggregates.AnalyticsReport", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_staff_metrics_analytics_reports_report_id");
                });

            modelBuilder.Entity("optiflow_platform.Clinical.Domain.Model.Entities.ClinicalRecord", b =>
                {
                    b.HasOne("optiflow_platform.Clinical.Domain.Model.Aggregates.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_clinical_records_patients_patient_id");
                });

            modelBuilder.Entity("optiflow_platform.Clinical.Domain.Model.Entities.Prescription", b =>
                {
                    b.HasOne("optiflow_platform.Clinical.Domain.Model.Entities.ClinicalRecord", null)
                        .WithMany()
                        .HasForeignKey("ClinicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_prescriptions_clinical_records_clinical_record_id");
                });
#pragma warning restore 612, 618
        }
    }
}
