namespace optiflow_platform.Analytics.Domain.Model.Entities;

/// <summary>
///     Staff metric entity representing individual employee performance for a report period.
/// </summary>
/// <remarks>
///     A staff metric belongs to an <see cref="Aggregates.AnalyticsReport"/> and records
///     the number of quotations issued, sales closed, and total revenue generated by a
///     single employee during the report period.
/// </remarks>
public class StaffMetric
{
    /// <summary>
    ///     Protected parameterless constructor for EF Core.
    /// </summary>
    protected StaffMetric()
    {
        EmployeeName = null!;
    }

    /// <summary>
    ///     Creates a new staff metric linked to an analytics report.
    /// </summary>
    public StaffMetric(int reportId, string employeeName, int quotationsIssued, int salesClosed, decimal totalRevenue)
    {
        ReportId          = reportId;
        EmployeeName      = employeeName;
        QuotationsIssued  = quotationsIssued;
        SalesClosed       = salesClosed;
        TotalRevenue      = totalRevenue;
    }

    public int     Id               { get; private set; }
    public int     ReportId         { get; private set; }
    public string  EmployeeName     { get; private set; }
    public int     QuotationsIssued { get; private set; }
    public int     SalesClosed      { get; private set; }
    public decimal TotalRevenue     { get; private set; }
}
