name: Deploy to Azure App Service

on:
  push:
    branches: [ main, feat/deployment ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore optiflow-platform/optiflow-platform.csproj

      - name: Publish
        run: dotnet publish optiflow-platform/optiflow-platform.csproj -c Release -r win-x86 --self-contained true -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: opti-flow-apiv1
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
